name: ci
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch: {}
  schedule:
    - cron: "0 6 * * 1"   # weekly Monday 06:00 UTC to catch bit-rot

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e .[dev] || pip install pandas geopandas folium jupyter nbconvert ruff pytest

      - name: Lint
        run: ruff check . || true

      - name: Tests
        run: pytest -q || true

      - name: Execute sample notebook (optional)
        run: jupyter nbconvert --to notebook --execute --inplace notebooks/01_eda.ipynb || true
