name: ci
on:
  push: { branches: ["**"] }
  pull_request: { branches: ["**"] }
  workflow_dispatch: {}

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install minimal deps
        run: |
          python -m pip install -U pip
          pip install pandas jupyter nbconvert ruff pytest

      - name: Lint (soft)
        run: ruff check . || true

      - name: Tests (soft)
        run: pytest -q || true

      - name: Execute notebooks if present
        if: ${{ hashFiles('notebooks/**/*.ipynb') != '' }}
        run: jupyter nbconvert --to notebook --execute --inplace notebooks/*.ipynb
